### PR TITLE
resolved dependency change in core discourse

### PR DESCRIPTION
**Pull request by oliver-walker-hms**
plugin is in a non-compilable state.
added in the fix here

### CODE REVIEW

**Comment by oliver-walker-hms** [comment]
The function 'build email' got moved to that new file that I added a require for

**Review by TomKimsey — CHANGES_REQUESTED** [review]
Commit message body needs more detail on why this change is needed.

**Comment by oliver-walker-hms** [comment]
added more detail to commit message

**Review by alexjhawk — APPROVED** [review]

**Review by TomKimsey — COMMENTED** [review]
This is okay but I think you should probably include why it got moved. To me reading this I have no idea why this file randomly "moved"
ex. build_email was moved to build_email_helper in discourse version 1.2.3

**Comment by oliver-walker-hms** [comment]
It's a bit of a hassle to track down when/why that change was introduced. I'm looking for more information for both of these PR's

**Comment by TomKimsey** [comment]
> It's a bit of a hassle to track down when/why that change was introduced. I'm looking for more information for both of these PR's

To be more clear i am not interested in why Discourse moved it, just what new discourse or plugin update moved that method.

**Comment by oliver-walker-hms** [comment]
ah, so it turns out in the commit message of when the change was introduced it was because they were specifically making it so you no longer need to use require_dependency which i used. i'll update both of these to the 'new' way of doing things which should have the same result with more standard ruby syntax

**Comment by TomKimsey** [comment]
sounds good

**Comment by oliver-walker-hms** [comment]
after looking into this more it seems like require dependecy is the better way to go for plugins and the 'zeitwerk' ruby gem was added for core discourse to use some new autoloader. https://github.com/fxn/zeitwerk/blob/master/README.md
I could also use require instead which doesn't have some sort of magical autoloading that require dependency has where if code gets changed it will autoload those changes into whatever is calling require_dependency. I am a little unclear on whether I should use require or require dependency. Require gets the job done. require dependency does the same but also has added in autoloading on file changes. Other discourse plugins seem to randomly switch between the two

**Comment by oliver-walker-hms** [comment]
on second thought, would you agree that using require is better? If I leave it as require dependency for that extra autoloading feature which I'm not entirely sure I understand how it works, I think it would just be catching real time code changes to the loaded code. require_dependency sounds not needed but not harmful. They both work for loading the code.

**Comment by TomKimsey** [comment]
I have no knowledge of ruby but it sounds like require_dependency is more feature rich in the fact that it allows you to update dependencies live. Its really up to you though. Is there any performance impact from using require_dependency? If its just checking when the server starts thats really not a big deal. If it checks anytime someone uses that plugins functionality I could see that being non ideal.

**Comment by oliver-walker-hms** [comment]
it was "strongly discouraged" to use autoloading in multi-threaded environments like discourse 8 years ago by the developers of ruby. I think that is no longer the case because of how often i see it, but not 100% sure. I'll try to measure the performance difference

**Comment by TomKimsey** [comment]
if require is all you require use require

**Comment by oliver-walker-hms** [comment]
I also just noticed I could not log in "create a new user session" because of this plugin. Just spent a good amount of time debugging and it was because the require does some weird stuff in the global scope. I needed to also require the base email class which the plugin does not use but the session manager uses to just be able to log in. seems really weird to me.

**Comment by TomKimsey** [comment]
> I also just noticed I could not log in "create a new user session" because of this plugin. Just spent a good amount of time debugging and it was because the require does some weird stuff in the global scope. I needed to also require the base email class which the plugin does not use but the session manager uses to just be able to log in. seems really weird to me.

Okay, just let me know when you get it working and you are ready for review.

**Review by TomKimsey — APPROVED** [review]

**Pull request merged**
